[package]
name = "read-idx-array"
authors = ["Ethan Williams"]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
nom = "7.1.3"

[dependencies.image]
version = "0.25.1"
default-features = false
